#!/bin/bash

# One of the following: xrandr, xbacklight, kernel
# METHOD="xbacklight"
METHOD="brightnessctl"

# Left click
#if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
#  xbacklight -inc 5
# Right click
#elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
#  xbacklight -dec 5
#fi

# case "$BLOCK_BUTTON" in
#     1) xbacklight -inc 5 ;; # left click
#     3) xbacklight -dec 5 ;; # right click
#     4) xbacklight -inc 2 ;; # scroll up
#     5) xbacklight -dec 2 ;; # scroll down
# esac

case "$BLOCK_BUTTON" in
    1) brightnessctl set +5% > /dev/null ;; # left click
    3) brightnessctl set 5%- > /dev/null ;; # right click
    4) brightnessctl set +5% > /dev/null ;; # scroll up
    5) brightnessctl set 5%- > /dev/null ;; # scroll down
esac

# URGENT_VALUE=10

if [[ "${METHOD}" = "xrandr" ]]; then
  device="${BLOCK_INSTANCE:-primary}"
  xrandrOutput=$(xrandr --verbose)

  if [[ "${device}" = "primary" ]]; then
    device=$(echo "${xrandrOutput}" | grep 'primary' | head -n 1 | awk -F ' ' '{print $1}')
  fi

  curBrightness=$(echo "${xrandrOutput}" | grep "${device}" -A 5 | grep -i "Brightness" | awk -F ':' '{print $2}')
elif [[ "${METHOD}" = "kernel" ]]; then
  device="${BLOCK_INSTANCE:-intel_backlight}"
  maxBrightness=$(cat /sys/class/backlight/${device}/max_brightness)
  curBrightness=$(cat /sys/class/backlight/${device}/brightness)
elif [[ "${METHOD}" = "xbacklight" ]]; then
  curBrightness=$(xbacklight -get)
elif [[ "${METHOD}" = "brightnessctl" ]]; then
  curBrightness=$(brightnessctl get)
  maxBrightness=$(brightnessctl max)
fi

# echo $curBrightness $maxBrightness

# if [[ "${curBrightness}" -le 0 ]]; then
#   exit
# fi

if [[ "${METHOD}" = "xrandr" ]]; then
  percent=$(echo "scale=0;${curBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "kernel" ]]; then
  percent=$(echo "scale=0;${curBrightness} / ${maxBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "xbacklight" ]]; then
  percent=$(echo "scale=0;${curBrightness}" | bc -l)
elif [[ "${METHOD}" = "brightnessctl" ]]; then
  percent=$(echo "scale=0;${curBrightness} * 100 / ${maxBrightness}" | bc -l)
fi

# echo $percent

percent=${percent%.*}

# if [[ "${percent}" -le 0 ]]; then
#   exit
# fi

echo "${percent}%"
echo "${percent}%"
#echo ""

# if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
#   exit 33
# fi
