#!/bin/bash

case "$BLOCK_BUTTON" in
    1) notify-send "left click"  ;; # left click
    3) notify-send "right click" ;; # right click
    4) notify-send "scroll up" ;; # scroll up
    5) notify-send "scroll down" ;; # scroll down
esac

echo "ok"
